website:
  title: "The Daddy long legs"                                # Your name
  description: "The daddy long legs"   # A brief slogan (optional)
  image: images/cover_pic.jpg
  favicon: favicon.png
  navbar:  
    pinned: true
    logo: favicon.png
    left:
      - text: "Magnus Volk"
        href: pages/magnus.qmd
      - text: "About the DLL"
        href: pages/dll.qmd
      - text: "Fish eye view"
        href: pages/fish.qmd
      - text: "Credits"
        href: pages/credits.qmd
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: |
      <span class="faux-block">&#169; 2024 Zachary Field CC BY-SA 4.0</span>

project:
  type: website
  output-dir: docs
  preview: 
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true
  render:
    - "*.qmd"
execute:
  freeze: true
  echo: false
  warnings: false
  message: false
format:
  html:
    fontsize: 1.1em
    theme:
      light: [pulse, html/styles.scss]
      dark: [darkly, html/styles.scss]
    toc: true
    toc_depth: 2
    toc-location: left
    toc-title: Chapters
    toc_float: true
    code-link: true
    highlight-style: ayu
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true



