---
title: "Credits"
---

This website was created by Zachary Field and his Dad. You can view the code at [https://github.com/profandyfield/volks_website](https://github.com/profandyfield/volks_website)

Zachary did the following:

- Researched all the information on the DLL
- Found images
- Wrote all of the scripts for the videos
- Wrote all of the text on the website
- Chose the costumes

Zachary's dad did the following:

- Set up the skeleton website using [quarto](https://quarto.org) a markdown-based system for writing html (and therefore easy for kids to learn)
- Filmed the videos
- Wrote this page

Team effort:

- Editing the videos: Dad showed Zachary what to do using [Camtasia](https://www.techsmith.com/camtasia) for the first video, then Zachary did the other videos (with some verbal prompts)
- Editing the website: Dad showed Zachary some basic Markdown, and helped him to use it to change the website menues, add links, insert the videos. Zachary pretended to be interested in [Github](https://github.com/) and [netlify](https://app.netlify.com))